INSERT INTO `adres` VALUES (1, 'Irysowa', 78, 12, 12341, 'Znamirowice');
INSERT INTO `adres` VALUES (2, 'Laczna', 39, 38, 13894, 'Stara Korytnica');
INSERT INTO `adres` VALUES (3, 'Gorna', 83, 64, 85860, 'Kędzierzyn-Koźle');
INSERT INTO `adres` VALUES (4, 'Gen. Swierczewskiego Karola', 93, 99, 79996, 'Mościcha');
INSERT INTO `adres` VALUES (5, 'Snopowa', 22, 82, 26811, 'Rudniki');
INSERT INTO `adres` VALUES (6, 'PCK', 20, 16, 22886, 'Chorzów');
INSERT INTO `adres` VALUES (7, 'Ojcowska', 61, 15, 18829, 'Lędziny');
INSERT INTO `adres` VALUES (8, 'Mlynowa', 92, 81, 89485, 'Rudno');
INSERT INTO `adres` VALUES (9, 'Zana Tomasza', 3, 1, 65595, 'Łeba');
INSERT INTO `adres` VALUES (10, 'Topolowa', 78, 61, 11739, 'Dąbrowa Górnicza');
INSERT INTO `adres` VALUES (11, 'Wilsona', 63, 24, 17294, 'Skarchowo');
INSERT INTO `adres` VALUES (12, 'Irysow', 28, 56, 33538, 'Olkowo');
INSERT INTO `adres` VALUES (13, 'Wodnika', 7, 47, 59934, 'Kraków');
INSERT INTO `adres` VALUES (14, 'Grottgera Artura', 7, 53, 13007, 'Łysaków');
INSERT INTO `adres` VALUES (15, 'Piastowski', 56, 85, 54650, 'Korzybie');
INSERT INTO `adres` VALUES (16, 'Imbramowska', 22, 1, 33152, 'Kraków');
INSERT INTO `adres` VALUES (17, 'Maślana', 21, 37, 00000, 'Warszawa');

INSERT INTO `certyfikat` VALUES (1, 'Trójbój poziom 1', 'Podstawy przysiadu, ogólne zagadnienia związane z rozwojem siły');
INSERT INTO `certyfikat` VALUES (2, 'Trójbój poziom 2', 'Podstawy wyciskania leżąc, martwego ciągu, zagadnienia zaawansowane związane z rozwojem siły');
INSERT INTO `certyfikat` VALUES (3, 'Trójbój poziom 3', 'Zaawansowana analiza przysiadu, wyciskania leżąc i martwego ciągu,  diagnoza oraz wzmocnienie słabych ogniw  w głównych bojach.');
INSERT INTO `certyfikat` VALUES (4, 'Zumba Basic 1', 'Poznanie głownych założeń i formuły Zumby. Podstawowe kroki i ich wariacje.');
INSERT INTO `certyfikat` VALUES (5, 'Zumba Rhytms 2', 'Taniec brzucha, flamenco, tango, samba, soca, quebradita - praca nad wzmocnieniem formuły Zumby, poprawa efektywności zajęć.');
INSERT INTO `certyfikat` VALUES (6, 'CrossFit poziom 1', 'Omówienie podstaw i rodzajów rozgrzewki, omówienie metodyki techniki ruchu oraz asekuracji, omówienie podstawowych ćwiczeń.');
INSERT INTO `certyfikat` VALUES (7, 'CrossFit poziom 2', 'Zaawansowanie przygotowanie motoryczne, omówienie zaawansowanych planów treningowych, przygowanie do zawodów.');
INSERT INTO `certyfikat` VALUES (8, 'Trener personalny', 'Podstawowe i zaawansowane zagadnienia związane z branżą fitness. Analiza ćwiczeń poprawiających sprawność fizyczną. Omówienie metod i praktyk związanych z pracą z klientem.');
INSERT INTO `certyfikat` VALUES (9, 'Dwubój olimpijski', 'Omówienie dyscypliny, przedstawienie zagadniej związanych z techniką w teorii i praktyce, budowa siły w dwuboju, omówienie cech motorycznych.');

INSERT INTO `czlonek` VALUES (1, 'Dawid', 'Wróbel', '2000-07-13', 'wrob@o2.pl', 1, 1, 1);
INSERT INTO `czlonek` VALUES (2, 'Kuba', 'Knap', '1990-07-27', 'qwd@wp.pl', 2, 2, 2);
INSERT INTO `czlonek` VALUES (3, 'Maciek', 'Sołtysik', '1995-02-13', 'maciek@gmail.com', 3, 4, 3);
INSERT INTO `czlonek` VALUES (4, 'Karol', 'Wadyła', '1972-04-04', 'wadyłaofficial@o2.pl', 4, 5, 4);
INSERT INTO `czlonek` VALUES (5, 'Karolina', 'Więga', '2001-06-05', 'karola@gmail.com', 5, 2, 5);
INSERT INTO `czlonek` VALUES (6, 'Magda', 'Poniatowska', '1960-01-01', 'magdalenawef@o2.pl', 6, 6, 6);
INSERT INTO `czlonek` VALUES (7, 'Marek', 'Purczynski', '1988-09-11', 'puczyn@gmail.com', 7, 1, 7);
INSERT INTO `czlonek` VALUES (8, 'Antoni', 'Kozak', '2002-11-12', 'kooz@gmail.com', 8, 3, 8);
INSERT INTO `czlonek` VALUES (9, 'Wasyli', 'Toszko', '1995-06-19', 'wasylTo@gmail.com', 9, 5, 9);
INSERT INTO `czlonek` VALUES (10, 'Aleksandra', 'Dąb', '1999-03-21', 'olaD@gmail.com', 10, 4, 10);
INSERT INTO `czlonek` VALUES (11, 'Filip', 'Fris', '1997-03-27', 'FreesFilip@gmail.com', 11, 5, 11);
INSERT INTO `czlonek` VALUES (12, 'Mariusz', 'Pudzianowski', '1975-06-02', 'polskagurom@o2.pl', 17, 4, 13);

INSERT INTO `czlonkostwo` VALUES (1, 'One-Time', 12, 'Karnet 1-dniowy, umożliwiający korzystanie z pełnej oferty klubu');
INSERT INTO `czlonkostwo` VALUES (2, 'Three-Times', 29, 'Karnet 3-dniowy, umożliwiający korzystanie z pełnej  oferty klubu');
INSERT INTO `czlonkostwo` VALUES (3, 'One-Week', 49, 'Karnet tygodniowy, umożliwiający korzystanie z pełnej oferty klubu');
INSERT INTO `czlonkostwo` VALUES (4, 'Open-Month', 99, 'Karnet miesięczny, umożliwiający korzystanie z pełnej oferty klubu');
INSERT INTO `czlonkostwo` VALUES (5, 'HalfOpen-Month', 79, 'Karnet miesięczny, umożliwiający korzystanie z pełnej oferty klubu w godzinach 6:00-15:00');
INSERT INTO `czlonkostwo` VALUES (6, 'Senior-Month', 69, 'Karnet miesięczny, umożliwiający korzystanie z pełnej oferty klubu, osoby powyżej 60 roku życia');

INSERT INTO `czlonkowie_i_zajecia` VALUES (1, 5);
INSERT INTO `czlonkowie_i_zajecia` VALUES (1, 10);
INSERT INTO `czlonkowie_i_zajecia` VALUES (1, 15);
INSERT INTO `czlonkowie_i_zajecia` VALUES (2, 3);
INSERT INTO `czlonkowie_i_zajecia` VALUES (2, 17);
INSERT INTO `czlonkowie_i_zajecia` VALUES (3, 1);
INSERT INTO `czlonkowie_i_zajecia` VALUES (3, 2);
INSERT INTO `czlonkowie_i_zajecia` VALUES (3, 26);
INSERT INTO `czlonkowie_i_zajecia` VALUES (4, 10);
INSERT INTO `czlonkowie_i_zajecia` VALUES (4, 31);
INSERT INTO `czlonkowie_i_zajecia` VALUES (5, 2);
INSERT INTO `czlonkowie_i_zajecia` VALUES (5, 4);
INSERT INTO `czlonkowie_i_zajecia` VALUES (5, 14);
INSERT INTO `czlonkowie_i_zajecia` VALUES (6, 2);
INSERT INTO `czlonkowie_i_zajecia` VALUES (6, 20);
INSERT INTO `czlonkowie_i_zajecia` VALUES (6, 30);
INSERT INTO `czlonkowie_i_zajecia` VALUES (7, 5);
INSERT INTO `czlonkowie_i_zajecia` VALUES (7, 9);
INSERT INTO `czlonkowie_i_zajecia` VALUES (7, 13);
INSERT INTO `czlonkowie_i_zajecia` VALUES (8, 1);
INSERT INTO `czlonkowie_i_zajecia` VALUES (8, 18);
INSERT INTO `czlonkowie_i_zajecia` VALUES (8, 23);
INSERT INTO `czlonkowie_i_zajecia` VALUES (8, 32);
INSERT INTO `czlonkowie_i_zajecia` VALUES (9, 1);
INSERT INTO `czlonkowie_i_zajecia` VALUES (9, 16);
INSERT INTO `czlonkowie_i_zajecia` VALUES (9, 24);
INSERT INTO `czlonkowie_i_zajecia` VALUES (9, 31);
INSERT INTO `czlonkowie_i_zajecia` VALUES (10, 1);
INSERT INTO `czlonkowie_i_zajecia` VALUES (10, 2);
INSERT INTO `czlonkowie_i_zajecia` VALUES (10, 11);
INSERT INTO `czlonkowie_i_zajecia` VALUES (10, 18);
INSERT INTO `czlonkowie_i_zajecia` VALUES (11, 7);
INSERT INTO `czlonkowie_i_zajecia` VALUES (11, 21);
INSERT INTO `czlonkowie_i_zajecia` VALUES (11, 26);

INSERT INTO `dzien_tygodnia` VALUES (1, 'Poniedziałek');
INSERT INTO `dzien_tygodnia` VALUES (2, 'Wtorek');
INSERT INTO `dzien_tygodnia` VALUES (3, 'Środa');
INSERT INTO `dzien_tygodnia` VALUES (4, 'Czwartek');
INSERT INTO `dzien_tygodnia` VALUES (5, 'Piątek');
INSERT INTO `dzien_tygodnia` VALUES (6, 'Sobota');
INSERT INTO `dzien_tygodnia` VALUES (7, 'Niedziela');

INSERT INTO `poziom_trudnosci_zajec` VALUES (1, 'początkujący');
INSERT INTO `poziom_trudnosci_zajec` VALUES (2, 'średnio-zaawansowany');
INSERT INTO `poziom_trudnosci_zajec` VALUES (3, 'zaawansowany');
INSERT INTO `poziom_trudnosci_zajec` VALUES (4, 'pro');

INSERT INTO `sala_cwiczen` VALUES (1, 'Strefa Eleiko');
INSERT INTO `sala_cwiczen` VALUES (2, 'Strefa Old-School');
INSERT INTO `sala_cwiczen` VALUES (3, 'Strefa wolnych ciężarów');
INSERT INTO `sala_cwiczen` VALUES (4, 'Strefa Cardio');
INSERT INTO `sala_cwiczen` VALUES (5, 'Strefa Crossfit');
INSERT INTO `sala_cwiczen` VALUES (6, 'Strefa Dance');

INSERT INTO `sprzet` VALUES (1, 'Eleiko 29mm 20kg', 5, 3);
INSERT INTO `sprzet` VALUES (2, 'Eleiko 25kg kalibrowane', 10, 2);
INSERT INTO `sprzet` VALUES (3, 'Eleiko 20kg kalibrowane', 10, 2);
INSERT INTO `sprzet` VALUES (4, 'Eleiko 15kg kalibrowane', 10, 2);
INSERT INTO `sprzet` VALUES (5, 'Eleiko 10kg kalibrowane', 10, 2);
INSERT INTO `sprzet` VALUES (6, 'Eleiko 5kg kalibrowane', 10, 2);
INSERT INTO `sprzet` VALUES (7, 'Eleiko 2.5kg kalibrowane', 10, 2);
INSERT INTO `sprzet` VALUES (8, 'HES 31mm 20kg ', 4, 3);
INSERT INTO `sprzet` VALUES (9, 'HES 25kg HexBar', 2, 3);
INSERT INTO `sprzet` VALUES (10, 'Eleiko Full płaska z asekuracją', 4, 4);
INSERT INTO `sprzet` VALUES (11, 'HES płaska z asekuracją', 2, 4);
INSERT INTO `sprzet` VALUES (12, 'Kettle 10kg', 6, 6);
INSERT INTO `sprzet` VALUES (13, 'Kettle 15kg', 6, 6);
INSERT INTO `sprzet` VALUES (14, 'Kettle 20kg', 6, 6);
INSERT INTO `sprzet` VALUES (15, 'Bieżnia', 10, 1);
INSERT INTO `sprzet` VALUES (16, 'Brama z regulowanym wyciągiem', 4, 1);
INSERT INTO `sprzet` VALUES (17, 'Eleiko regulowany stojak klasyczny', 5, 5);
INSERT INTO `sprzet` VALUES (18, 'HES Monolift', 2, 5);

INSERT INTO `sprzet_czlonek_wypozyczalnia` VALUES (1, 1, 1);
INSERT INTO `sprzet_czlonek_wypozyczalnia` VALUES (7, 1, 1);
INSERT INTO `sprzet_czlonek_wypozyczalnia` VALUES (1, 2, 2);
INSERT INTO `sprzet_czlonek_wypozyczalnia` VALUES (7, 3, 4);
INSERT INTO `sprzet_czlonek_wypozyczalnia` VALUES (1, 5, 2);
INSERT INTO `sprzet_czlonek_wypozyczalnia` VALUES (7, 11, 1);
INSERT INTO `sprzet_czlonek_wypozyczalnia` VALUES (5, 12, 2);
INSERT INTO `sprzet_czlonek_wypozyczalnia` VALUES (10, 12, 2);
INSERT INTO `sprzet_czlonek_wypozyczalnia` VALUES (5, 13, 2);
INSERT INTO `sprzet_czlonek_wypozyczalnia` VALUES (4, 15, 1);
INSERT INTO `sprzet_czlonek_wypozyczalnia` VALUES (1, 17, 1);

INSERT INTO `trener` VALUES (1, 'Konrad', 'Kot', 3, 12);
INSERT INTO `trener` VALUES (2, 'Aleksander', 'Wielki', 6, 13);
INSERT INTO `trener` VALUES (3, 'Karol', 'Duży', 4, 14);
INSERT INTO `trener` VALUES (4, 'Wiktoria', 'Nycz', 2, 15);

INSERT INTO `trenerzy_i_certyfikaty` VALUES (1, 1);
INSERT INTO `trenerzy_i_certyfikaty` VALUES (2, 1);
INSERT INTO `trenerzy_i_certyfikaty` VALUES (1, 2);
INSERT INTO `trenerzy_i_certyfikaty` VALUES (1, 3);
INSERT INTO `trenerzy_i_certyfikaty` VALUES (4, 4);
INSERT INTO `trenerzy_i_certyfikaty` VALUES (4, 5);
INSERT INTO `trenerzy_i_certyfikaty` VALUES (2, 6);
INSERT INTO `trenerzy_i_certyfikaty` VALUES (2, 7);
INSERT INTO `trenerzy_i_certyfikaty` VALUES (1, 8);
INSERT INTO `trenerzy_i_certyfikaty` VALUES (2, 8);
INSERT INTO `trenerzy_i_certyfikaty` VALUES (3, 8);
INSERT INTO `trenerzy_i_certyfikaty` VALUES (4, 8);
INSERT INTO `trenerzy_i_certyfikaty` VALUES (3, 9);

INSERT INTO `typ_sprzetu` VALUES (1, 'maszyna');
INSERT INTO `typ_sprzetu` VALUES (2, 'obciążenie');
INSERT INTO `typ_sprzetu` VALUES (3, 'sztanga');
INSERT INTO `typ_sprzetu` VALUES (4, 'ławka');
INSERT INTO `typ_sprzetu` VALUES (5, 'stojak');
INSERT INTO `typ_sprzetu` VALUES (6, 'Kettle');
INSERT INTO `typ_sprzetu` VALUES (7, 'Hantle');

INSERT INTO `typ_zajec` VALUES (1, 'Ogólnorozwojowe');
INSERT INTO `typ_zajec` VALUES (2, 'Zumba');
INSERT INTO `typ_zajec` VALUES (3, 'Dwubój');
INSERT INTO `typ_zajec` VALUES (4, 'Trójbój siłowy');

INSERT INTO `wyniki_sportowe` VALUES (1, 200, 140, 220, 110, 140, '00:03:10', 50, 22);
INSERT INTO `wyniki_sportowe` VALUES (2, 170, 110, 165, 77, 95, '00:02:55', 45, 15);
INSERT INTO `wyniki_sportowe` VALUES (3, 120, 85, 134, 60, 0, '00:00:00', 37, 11);
INSERT INTO `wyniki_sportowe` VALUES (4, 250, 175, 280, 165, 180, '00:00:00', 40, 10);
INSERT INTO `wyniki_sportowe` VALUES (5, 70, 45, 85, 0, 0, '00:03:45', 20, 5);
INSERT INTO `wyniki_sportowe` VALUES (6, 0, 0, 0, 0, 0, '00:05:44', 0, 0);
INSERT INTO `wyniki_sportowe` VALUES (7, 140, 100, 158, 70, 110, '00:03:30', 70, 35);
INSERT INTO `wyniki_sportowe` VALUES (8, 160, 111, 176, 95, 110, '00:02:49', 60, 28);
INSERT INTO `wyniki_sportowe` VALUES (9, 95, 70, 100, 0, 0, '00:02:59', 40, 19);
INSERT INTO `wyniki_sportowe` VALUES (10, 60, 40, 115, 135, 155, '00:01:58', 30, 10);
INSERT INTO `wyniki_sportowe` VALUES (11, 96, 90, 115, 65, 88, '00:02:01', 28, 8);
INSERT INTO `wyniki_sportowe` VALUES (12, 230, 175, 265, 150, 175, '00:04:02', 75, 28);
INSERT INTO `wyniki_sportowe` VALUES (13, 410, 270, 400, 180, 200, '00:02:04', 100, 45);

INSERT INTO `zajecia_dzien_tygodnia` VALUES (1, 1, 1);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (2, 2, 1);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (3, 3, 1);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (4, 4, 1);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (5, 5, 1);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (6, 1, 4);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (7, 2, 4);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (8, 3, 4);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (9, 4, 4);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (10, 5, 4);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (11, 6, 2);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (12, 7, 2);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (13, 8, 2);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (14, 9, 2);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (15, 10, 2);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (16, 6, 5);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (17, 7, 5);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (18, 8, 5);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (19, 9, 5);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (20, 10, 5);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (21, 11, 3);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (22, 12, 3);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (23, 13, 3);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (24, 14, 3);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (25, 15, 3);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (26, 11, 6);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (27, 12, 6);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (28, 13, 6);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (29, 14, 6);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (30, 15, 6);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (31, 16, 7);
INSERT INTO `zajecia_dzien_tygodnia` VALUES (32, 17, 7);

INSERT INTO `zajecia_sportowe` VALUES (1, '07:30:00', DEFAULT, 2, 4, 1, 6, '01:30:00');
INSERT INTO `zajecia_sportowe` VALUES (2, '09:15:00', DEFAULT, 1, 2, 1, 5, '01:30:00');
INSERT INTO `zajecia_sportowe` VALUES (3, '11:00:00', DEFAULT, 3, 3, 1, 1, '02:30:00');
INSERT INTO `zajecia_sportowe` VALUES (4, '14:00:00', DEFAULT, 1, 4, 1, 5, '01:30:00');
INSERT INTO `zajecia_sportowe` VALUES (5, '16:00:00', DEFAULT, 4, 1, 1, 3, '02:30:00');
INSERT INTO `zajecia_sportowe` VALUES (6, '07:30:00', DEFAULT, 2, 4, 2, 6, '01:30:00');
INSERT INTO `zajecia_sportowe` VALUES (7, '09:15:00', DEFAULT, 1, 2, 2, 5, '01:30:00');
INSERT INTO `zajecia_sportowe` VALUES (8, '11:00:00', DEFAULT, 3, 3, 2, 1, '02:30:00');
INSERT INTO `zajecia_sportowe` VALUES (9, '14:00:00', DEFAULT, 1, 4, 2, 5, '01:30:00');
INSERT INTO `zajecia_sportowe` VALUES (10, '16:00:00', DEFAULT, 4, 1, 2, 3, '02:30:00');
INSERT INTO `zajecia_sportowe` VALUES (11, '07:30:00', DEFAULT, 2, 4, 3, 6, '01:30:00');
INSERT INTO `zajecia_sportowe` VALUES (12, '09:15:00', DEFAULT, 1, 2, 3, 5, '01:30:00');
INSERT INTO `zajecia_sportowe` VALUES (13, '11:00:00', DEFAULT, 3, 3, 3, 1, '02:30:00');
INSERT INTO `zajecia_sportowe` VALUES (14, '14:00:00', DEFAULT, 1, 4, 3, 5, '01:30:00');
INSERT INTO `zajecia_sportowe` VALUES (15, '16:00:00', DEFAULT, 4, 1, 3, 3, '02:30:00');
INSERT INTO `zajecia_sportowe` VALUES (16, '11:00:00', DEFAULT, 3, 3, 4, 1, '02:30:00');
INSERT INTO `zajecia_sportowe` VALUES (17, '16:00:00', DEFAULT, 4, 1, 4, 3, '02:30:00');





